[project]
name = "relate_py"
version = "0.1.0"
authors = [{ name = "Tang Ziya", email = "tcztzy@hotmail.com" }]
dependencies = [
    "click==8.1.3",
    "click-log==0.4.0",
    "cython==3.0.0a11",
]

[build-system]
requires = ["pyproject-toml==0.0.10"]
build-backend = "pyproject_toml.build_system.build_backend"
